collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8655914
  brandStrength: 0.7249538
  lightness: 0.2885305
  brandColors:
    - '#100F1D'
    - '#FBFFFF'
    - '#16425C'
    - '#1FCFF2'
    - '#0188A3'
  rhythmicContrast: 0.6477612
typography_spectrum: 0.750896
layout_spectrum: 0.1827957
name: IoT news
