collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.750896
color:
  saturation: 0.8599657
  brandStrength: 0.7249538
  lightness: 0.07814562
  brandColors:
    - '#100F1D'
    - '#FBFFFF'
    - '#16425C'
    - '#1FCFF2'
    - '#0188A3'
  rhythmicContrast: 0.6477612
layout_spectrum: 0.7741935
name: IoT news
